image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_REF_NAME =~ /^v\d+\.\d+\.\d+.*$/
      changes:
        - package.json
  script:
    - npm config set @scope:registry https://registry.npmjs.org/
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm ci
#    - npm publish --verbose